import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("supply_chain_data.csv")
warehouse_time = df['Manufacturing lead time'].values
transport_time = df['Shipping times'].values
delivery_time = df['Lead times'].values
warehouse_avg = np.mean(warehouse_time)
transport_avg = np.mean(transport_time)
delivery_avg = np.mean(delivery_time)
warehouse_max = np.max(warehouse_time)
transport_max = np.max(transport_time)
delivery_max = np.max(delivery_time)
warehouse_min = np.min(warehouse_time)
transport_min = np.min(transport_time)
delivery_min = np.min(delivery_time)
print("\nLEAD-TIME ANALYSIS")
print("-----------------------------")
print("Warehouse → Avg:", warehouse_avg, "Max:", warehouse_max, "Min:", warehouse_min)
print("Transport → Avg:", transport_avg, "Max:", transport_max, "Min:", transport_min)
print("Delivery  → Avg:", delivery_avg, "Max:", delivery_max, "Min:", delivery_min)
stages = ['Warehouse', 'Transport', 'Delivery']
avg_delays = [warehouse_avg, transport_avg, delivery_avg]
plt.figure()
plt.bar(stages, avg_delays)
plt.title("Stage-wise Average Delay")
plt.xlabel("Supply Chain Stage")
plt.ylabel("Delay Time")
plt.show()
warehouse_var = np.var(warehouse_time)
transport_var = np.var(transport_time)
delivery_var = np.var(delivery_time)
print("\nBOTTLENECK DETECTION (VARIANCE)")
print("-----------------------------")
print("Warehouse Variance:", warehouse_var)
print("Transport Variance:", transport_var)
print("Delivery Variance:", delivery_var)
variance_values = [warehouse_var, transport_var, delivery_var]
bottleneck_stage = stages[np.argmax(variance_values)]
print("Identified Bottleneck Stage:", bottleneck_stage)
plt.figure()
plt.bar(stages, variance_values)
plt.title("Delay Variance by Stage (Bottleneck Detection)")
plt.xlabel("Stage")
plt.ylabel("Variance")
plt.show()
fulfillment_rate = (df['Availability'] / df['Order quantities']) * 100
avg_fulfillment = np.mean(fulfillment_rate)
min_fulfillment = np.min(fulfillment_rate)
print("\nORDER FULFILLMENT ANALYSIS")
print("-----------------------------")
print("Average Fulfillment Rate:", round(avg_fulfillment, 2), "%")
print("Minimum Fulfillment Rate:", round(min_fulfillment, 2), "%")
plt.figure()
plt.plot(fulfillment_rate)
plt.title("Order Fulfillment Rate Trend")
plt.xlabel("Order Index")
plt.ylabel("Fulfillment Rate (%)")
plt.show()
plt.figure()
plt.scatter(df['Shipping times'], df['Shipping costs'])
plt.title("Cost vs Delivery-Time Tradeoff")
plt.xlabel("Delivery Time (Shipping)")
plt.ylabel("Shipping Cost")
plt.show()
order_quantities = df['Order quantities'].values
moving_avg_demand = np.convolve(order_quantities, np.ones(10)/10, mode='valid')
plt.figure()
plt.plot(order_quantities, label='Original Demand')
plt.plot(moving_avg_demand, label='Demand Trend', linewidth=3)
plt.title("Seasonal Demand Pattern Visualization")
plt.xlabel("Order Index")
plt.ylabel("Order Quantity")
plt.legend()
plt.show()
print("\nFINAL PROJECT INSIGHTS")
print("-----------------------------")
print("Slowest Stage in Supply Chain:", bottleneck_stage)
print("Average Fulfillment Rate:", round(avg_fulfillment, 2), "%")
print("Operational Recommendation:")
print("- Improve efficiency at", bottleneck_stage)
print("- Optimize scheduling and logistics planning")
print("- Reduce delays to lower operational costs")
